# Generated by Django 3.1.2 on 2020-10-20 00:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leshab', '0002_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linesm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('geometr', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('polyg', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
