# Generated by Django 3.1.2 on 2020-10-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leshab', '0006_lamp_historique'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamp_historique',
            name='created_At',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
