# Generated by Django 3.1.2 on 2020-11-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0007_lamp_historique_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delm',
        ),
        migrations.DeleteModel(
            name='Zipcode',
        ),
    ]
