# Generated by Django 3.1.2 on 2020-11-11 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0010_auto_20201111_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToSup',
        ),
        migrations.AlterField(
            model_name='lamp_historique',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 12, 41, 55, 793301)),
        ),
    ]
