# Generated by Django 3.1.2 on 2020-11-11 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0013_auto_20201111_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp_historique',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 17, 11, 41, 870523)),
        ),
    ]
