# Generated by Django 3.1.2 on 2020-11-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0015_auto_20201111_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp_historique',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
