"""
Django settings for lampProject project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# we will use the env.json file for the settings
import json

with open('lampProject/env.json') as file:
    jsonFile = json.load(file)
    DB_ENV = jsonFile['DB']
    hosts = jsonFile['ALLOWED_HOSTS']
    key = jsonFile['SECRET_KEY']
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = key

ENVIRONNEMENT = 'PROD'

# SECURITY WARNING: don't run with debug turned on in production!
if ENVIRONNEMENT == 'DEV':
    DEBUG = True
else:
    DEBUG = False #we will turn debug to false in a prod or preprod env


ALLOWED_HOSTS = hosts


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'geoapi.apps.GeoapiConfig',
    'django.contrib.gis',
    'corsheaders',
    'rest_framework',
    'rest_framework_gis',
    'django_rename_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',


    'whitenoise.middleware.WhiteNoiseMiddleware',


    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

]

ROOT_URLCONF = 'lampProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True, #Ici on dit a django d'aller chercher les templates au sein des applications
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lampProject.wsgi.application'

CORS_ALLOW_ALL_ORIGINS = True




if ENVIRONNEMENT == 'DEV':
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': DB_ENV ['DEV']['NAME'],
            'USER': DB_ENV ['DEV']['USER'],
            'PASSWORD': DB_ENV ['DEV']['PASSWORD'],
            'HOST': DB_ENV ['DEV']['HOST'],
            'PORT': DB_ENV ['DEV']['PORT'],
        }
    }
elif ENVIRONNEMENT == 'PREPROD':
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': DB_ENV ['PREPROD']['NAME'],
            'USER': DB_ENV ['PREPROD']['USER'],
            'PASSWORD': DB_ENV ['PREPROD']['PASSWORD'],
            'HOST': DB_ENV ['PREPROD']['HOST'],
            'PORT': DB_ENV ['PREPROD']['PORT'],
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': DB_ENV ['PROD']['NAME'],
            'USER': DB_ENV ['PROD']['USER'],
            'PASSWORD': DB_ENV ['PROD']['PASSWORD'],
            'HOST': DB_ENV ['PROD']['HOST'],
            'PORT': DB_ENV ['PROD']['PORT'],
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

STATIC_URL = 'geoapi/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'geoapi/static')
]

